#r "nuget: DSharpPlus, 4.1.0"
#r "nuget: DSharpPlus.CommandsNext, 4.1.0"
#r "nuget: Fake.Core.Process, 5.21.1"
#r "nuget: FParsec, 1.1.1"
#r "nuget: MathNet.Numerics, 4.15.0"
#r "nuget: SchlenkR.FsHttp, 5.0.0"
#r "nuget: Thoth.Json.Net, 5.0.0"
#load "Extensions.fs"
#load "Util.fs"
#load "Types.fs"
#load "Data.fs"
#load "Calculator.fs"
#load "Commands.fs"
